name: note
on: push
jobs:
  all:
    env:
      GO111MODULE: on
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - working-directory: ./adir
        run: copy afile.txt ..
      - run: dir
      
     
