name: note
on: push
jobs:
  all:
    env:
      GO111MODULE: on
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          go-version: '1.16.3'
      - uses: actions/setup-go@v2
      - run: go build -v
